POST http://localhost:3000/user/sign-up HTTP/1.1
content-type: application/json

{
  "email": "admin@a.com",
  "password": "pass",
  "type": "admin"
}

###

POST http://localhost:3000/user/sign-in HTTP/1.1
content-type: application/json

{
  "email": "admin@a.com",
  "password": "pass"
}
