POST http://localhost:3001/user/sign-up HTTP/1.1
content-type: application/json

{
  "email": "admin@a.com",
  "password": "pass",
  "type": "admin"
}

###

POST http://localhost:3001/user/sign-in HTTP/1.1
content-type: application/json

{
  "email": "admin@a.com",
  "password": "pass"
}

###

POST http://localhost:3001/fl/create-profile HTTP/1.1
content-type: application/json

{
  "fname": "flan",
  "lname": "alflani",
  "email": "dev@dev.com",
  "phone_num": "+465645",
  "country": "sudan",
  "city": "omdour",
  "profile_title": "dev",
  "sector": "web dev",
  "skills": ["fr","en","ar"],
  "languages": ["fr","en","ar"],
  "user_id": 2
}

###

POST http://localhost:3001/fl/add-experiences HTTP/1.1
content-type: application/json

{
  "experiences": [
    {
      "sector": "web dev",
      "employer": "devboite",
      "description": "alfladfgdfgdfg dfgdfgni",
      "skills": "fr",
      "from_date": "2018-05-25",
      "to_date": "2019-01-09",
      "user_id": 2
    },
    {
      "sector": "mobile dev",
      "employer": "tech2",
      "description": "alfladfgdfgdfg dfgdfgni",
      "skills": "en",
      "from_date": "2019-06-05",
      "to_date": "2020-01-28",
      "user_id": 2
    }
  ]
}

###

POST http://localhost:3001/fl/add-education HTTP/1.1
content-type: application/json

{
  "education": [
    {
      "title": "dev",
      "institution": "simplon",
      "country": "frence",
      "graduation_year": "2021",
      "user_id": 2
    }
  ]
}

###

POST http://localhost:3001/em/create-profile HTTP/1.1
content-type: application/json

{
  "fname": "flan",
  "lname": "alflani",
  "email": "dev@dev.com",
  "phone_num": "465645",
  "country": "sudan",
  "city": "omdour",
  "user_id": 3
}

###

POST http://localhost:3001/job/post-job HTTP/1.1
content-type: application/json

{
  "job_title": "job1",
  "job_description": "alflsdfsdfsdf fdsfdsfani",
  "required_sector": "dev web",
  "required_skills": "react",
  "num_freelancer_required": "1",
  "duration": "one week",
  "budget": 1000,
  "job_status": "in process",
  "user_id": 3
}

###

DELETE http://localhost:3001/job/delete-job/2 HTTP/1.1
content-type: application/json

###

GET http://localhost:3001/em/employer/3 HTTP/1.1
content-type: application/json
