// user types
export const USER_LOADING = "USER_LOADING"
export const USER_LOADED = "USER_LOADED"
export const AUTH_ERROR = "AUTH_ERROR"
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS"
export const SIGNIN_FAIL = "SIGNIN_FAIL"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAIL = "SIGNUP_FAIL"
export const SIGN_OUT = 'SIGN_OUT'

//employer types
export const EM_CREATE_SUCCESS = "EM_CREATE_SUCCESS"
export const EMPLOYER_LOADING = "EMPLOYER_LOADING"
export const EMPLOYER_LOADED = "EMPLOYER_LOADED"
export const EM_NOT_FOUNDED = "EM_NOT_FOUNDED"
export const CLEAR_EMPLOYER = "CLEAR_EMPLOYER"

//employer types
export const FR_CREATE_SUCCESS = "FR_CREATE_SUCCESS"
export const EX_ADDED_SUCCESS = "EX_ADDED_SUCCESS"
export const PROFILE_LOADED = "PROFILE_LOADED"
export const EMPLOYERS_LOADED = "EMPLOYERS_LOADED"
export const FR_NOT_FOUNDED = "FR_NOT_FOUNDED"
export const EX_NOT_FOUNDED = "EX_NOT_FOUNDED"
export const EXPERIENCES_LOADED = "EXPERIENCES_LOADED"
export const CLEAR_FREELANCER = "CLEAR_FREELANCER"

//project types
export const PROJECTS_LOADED = "PROJECTS_LOADED"
export const ALL_PROFILES_LOADED = "ALL_PROFILES_LOADED"
export const PROFILES_NOT_FOUNDED = "PROFILES_NOT_FOUNDED"
export const APPLICATIONS_LOADED = "APPLICATION_LOADED"
export const NO_APPLINTIONS = "APPLICATION_LOADED"
export const CLEAR_PROJECTS = "CLEAR_PROJECTS"
export const CATEGORIES_LOADED = "CATEGORIES_LOADED"
export const SKILLS_LOADED = "SKILLS_LOADED"


// errors types
export const GET_ERRORS = 'GET_ERRORS'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'